In [1]:
import torch
from torch.autograd import Function
from entmax.root_finding import entmax_bisect
from bisection import EntmaxBisectFunction
from nsection import EntmaxNsectFunction

In [2]:
input_mat = torch.randn(10, 30000)

In [3]:
%time EntmaxBisectFunction.forward(Function, input_mat, n_iter=50)

CPU times: total: 594 ms
Wall time: 103 ms


tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [4]:
%time EntmaxNsectFunction.forward(Function, input_mat, n_iter=5, n_sections=5)

CPU times: total: 281 ms
Wall time: 51 ms


tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [5]:
%time EntmaxNsectFunction.forward(Function, input_mat, n_iter=3, n_sections=10)

CPU times: total: 375 ms
Wall time: 70 ms


tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [6]:
%time entmax_bisect(input_mat)

CPU times: total: 766 ms
Wall time: 140 ms


tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])